config/routes.rb
Rails.application.routes.draw do
  
	resources 'users', only: [:new, :create, :show, :index, :edit, :update, :destroy]

  get '/login', to: 'session#new'
  post '/login', to: 'session#create'
  delete '/login', to: 'session#destroy'
  
  get '/universe', to: 'universe#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	#before_save { self.email = email.downcase }
	validates :email, presence: true

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true,
	length: { maximum: 255 },
	format: { with: VALID_EMAIL_REGEX },
	uniqueness: { case_sensitive: false }
  
	has_secure_password
	validates :password, presence: true, length: { minimum: 6, maximum: 255 }
	

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionHelper
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
  	form_email = params[:formulaire_login][:email]
  	form_password = params[:formulaire_login][:password]
  	user = User.find_by(email:form_email)
  	if user && user.authenticate(form_password)
  		log_in(user)
  		puts "MARCHE !!"
  		puts session[:user_id]
  		redirect_to users_path
  		#Create the session
  	else
  		render "new"
  	end

  end

 	def destroy
 		log_out
 		redirect_to login_path
  end

end

app/controllers/universe_controller.rb
class UniverseController < ApplicationController

  def index
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:email, :password)
    @user = User.new
    @user.assign_attributes(user_params)

    if @user.valid? == false
      render 'new'
    else
      @user.save(user_params)
      log_in(@user)
      redirect_to users_path
    end

  end

  def index
  end

  def show
  end

  def edit
    @user = User.find(current_user.id)
  end

  def update
    puts "//////////"
    user_params = params.require(:user).permit(:email, :password)
    @user = User.find(current_user.id)
    @user.assign_attributes(user_params)
    
    if @user.valid? == false
      render 'edit'
    else
      @user.update(user_params)
      redirect_to users_path
    end

  end

  def destroy
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper

	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
	end

	def logged_in?
		!current_user.nil?
	end

	def log_out
		session.delete(:user_id)
	end

end

app/helpers/universe_helper.rb
module UniverseHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <span class="navbar-brand">The Secret World</span>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">

    		<% if logged_in? %>
          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_path(current_user.id), class: "nav-link" %>
          </li>        
    		  <li class="nav-item">
      			<%= link_to "Logout", login_path, method: :delete, class: "nav-link" %>
      		</li>
  	  	<% else %>
      		<li class="nav-item">      		
      			<%= link_to "Login", login_path, class: "nav-link" %>
      		</li>
      		<li class="nav-item">      		
      			<%= link_to "Sign up", new_user_path, class: "nav-link" %>
      		</li>
    		<% end %>
    </ul>

  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Secret</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>

  <body>
    <%= render "layouts/header" %>
    <% if logged_in? == false && current_page?(:controller => 'session', :action => 'new') || logged_in? == false && current_page?(:controller => 'users', :action => 'new') %>
      <%= yield %>
    <% elsif logged_in? %>
      <%= yield %>
    <% else %>
      <div style="margin-top: 50px; width: 40%; margin-left: auto; margin-right: auto; background-color: lightgrey; padding: 50px; text-align: center;" class="rounded" class="border border-light">
        Tu ne peux obtenir aucun secret...
      </div>    
    <% end %>

  </body>
</html>

app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>

app/views/session/new.html.erb
<div style="margin-top: 50px; width: 40%; margin-left: auto; margin-right: auto; background-color: lightgrey; padding: 50px;" class="rounded" class="border border-light">
	<h1>Bienvenue sur la page de login</h1>
	<p>Veuillez vous authentifier :</p>

	<%= form_for :formulaire_login do |f| %>
	  <div class="form-group">
			<%= f.label :email, "Email" %>
			<br />
			<%= f.text_field :email, placeholder: "Votre adresse e-mail...", class: "form-control" %>
  	</div>
	  <div class="form-group">
		<%= f.label :password, "Password" %>
		<br />
		<%= f.password_field :password, placeholder: "Votre mot de passe...", class: "form-control" %>
  	</div>

		<%= f.submit "Login", class:"btn btn-success" %>

	<% end %>
</div>

app/views/universe/index.html.erb
<div style="margin-top: 50px; width: 40%; margin-left: auto; margin-right: auto; background-color: lightgrey; padding: 50px; text-align: center;" class="rounded" class="border border-light">
	<iframe width="560" height="315" src="https://www.youtube.com/embed/eaW0tYpxyp0" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>

app/views/users/create.html.erb
<div style="margin-top: 50px; width: 40%; margin-left: auto; margin-right: auto; background-color: lightgrey; padding: 50px;" class="rounded" class="border border-light">
	Confirmation d'inscription
</div>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<div style="margin-top: 50px; width: 40%; margin-left: auto; margin-right: auto; background-color: lightgrey; padding: 50px;" class="rounded" class="border border-light">
	<h1>Edite ton profil</h1>



	<%= form_for @user do |f| %>
	  <div class="form-group">
			<%= f.label :email, "Email" %>
			<br />
			<%= f.text_field :email, placeholder: "Votre adresse e-mail...", class: "form-control" %>
  	</div>
	  <div class="form-group">
			<%= f.label :password, "Password" %>
		<br />
			<%= f.password_field :password, placeholder: "Votre mot de passe...", class: "form-control" %>
  	</div>

		<%= f.submit "Editer le profil", class:"btn btn-success" %>

	<% end %>
</div>

app/views/users/index.html.erb
<div style="margin-top: 50px; width: 40%; margin-left: auto; margin-right: auto; background-color: lightgrey; padding: 50px;" class="rounded" class="border border-light">
		Bienvenue à toi qui possède l'adresse e-mail <%= current_user.email %>
		<br /><br />
		Souhaites-tu obtenir la réponse à la question de l'univers ?
		<br />
		<br />
		Voici le lien vers cette réponse : <%= link_to "Universe Response", universe_path %> !
</div>

app/views/users/new.html.erb
<div style="margin-top: 50px; width: 40%; margin-left: auto; margin-right: auto; background-color: lightgrey; padding: 50px;" class="rounded" class="border border-light">
	<h1>Bienvenue sur la page d'inscription</h1>

	<%= form_for @user do |f| %>
	  <div class="form-group">
			<%= f.label :email, "Email" %>
			<br />
			<%= f.text_field :email, placeholder: "Votre adresse e-mail...", class: "form-control" %>
  	</div>
	  <div class="form-group">
			<%= f.label :password, "Password" %>
		<br />
			<%= f.password_field :password, placeholder: "Votre mot de passe...", class: "form-control" %>
  	</div>

		<%= f.submit "S'inscrire", class:"btn btn-success" %>

	<% end %>
</div>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>